#!/usr/bin/env python3
"""Apply the agreed index vocabulary to the manuscript.

Reads refs/index-vocabulary.tsv and inserts \\aidx{key} (defined as \\index in
the preamble) after the FIRST occurrence of any alias in each \\section of each
chapter content file. Fully regenerable: every existing \\aidx{...} is stripped
first, so editing the vocabulary and re-running converges. Hand-written
\\index{...} commands are never touched.

Skips: comment lines, display-math environments, \\caption/\\section/\\subsection
arguments, and aliases containing TeX markup (those exist in the vocabulary for
reference; anchor them by hand with \\index{} where wanted).

Cross-reference rows (alias column 'SEE:<target>') are emitted once into
refs/index-see-entries.tex, which main.tex inputs before \\printindex.
"""
import pathlib, re, sys

REPO = pathlib.Path(__file__).resolve().parent.parent
VOCAB = REPO / "refs/index-vocabulary.tsv"
MATH_ENVS = ("equation", "align", "gather", "multline", "eqnarray", "displaymath")

def load_vocab():
    plain, see = [], []
    for line in VOCAB.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        parts = line.split("\t")
        key, alias_field = parts[0], parts[1] if len(parts) > 1 else ""
        if alias_field.startswith("SEE:"):
            see.append((key, alias_field[4:]))
            continue
        aliases = [a for a in alias_field.split(";")
                   if a and not re.search(r"[\\${}_^]", a) and len(a) > 2]
        if aliases:
            plain.append((key, sorted(aliases, key=len, reverse=True)))
    return plain, see

def sections(text):
    """Yield (start, end) spans of \\section-delimited blocks."""
    marks = [m.start() for m in re.finditer(r"\\section\{", text)] or [0]
    if marks[0] != 0:
        marks.insert(0, 0)
    marks.append(len(text))
    return list(zip(marks[:-1], marks[1:]))

def skip_mask(text):
    """Boolean mask: True where insertion is forbidden."""
    mask = bytearray(len(text))
    # comments
    for m in re.finditer(r"(?m)%.*$", text):
        for i in range(m.start(), m.end()): mask[i] = 1
    # display math environments
    for env in MATH_ENVS:
        for m in re.finditer(r"\\begin\{%s\*?\}.*?\\end\{%s\*?\}" % (env, env), text, re.S):
            for i in range(m.start(), m.end()): mask[i] = 1
    # inline math
    for m in re.finditer(r"\$[^$]*\$", text):
        for i in range(m.start(), m.end()): mask[i] = 1
    # captions and headings (first brace group, non-nested approximation)
    for m in re.finditer(r"\\(caption|section|subsection|subsubsection|chapter|label|ref|eqref|cite|includegraphics|redrawcompare)\{[^{}]*\}", text):
        for i in range(m.start(), m.end()): mask[i] = 1
    return mask

def apply_file(path, vocab):
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"\\aidx\{[^{}]*\}", "", text)  # strip previous run
    mask = skip_mask(text)
    inserts = []  # (pos, key)
    for start, end in sections(text):
        for key, aliases in vocab:
            found = None
            for alias in aliases:
                for m in re.finditer(r"(?<![A-Za-z\\])" + re.escape(alias), text[start:end]):
                    p0, p1 = start + m.start(), start + m.end()
                    if not any(mask[p0:p1]):
                        found = p1
                        break
                if found:
                    break
            if found:
                inserts.append((found, key))
    for pos, key in sorted(inserts, reverse=True):
        text = text[:pos] + "\\aidx{" + key + "}" + text[pos:]
    path.write_text(text, encoding="utf-8")
    return len(inserts)

def main():
    plain, see = load_vocab()
    total = 0
    for f in sorted(REPO.glob("chapters/*/*.tex")):
        if f.name.startswith("ch") and f.name[2:4].isdigit():
            continue  # wrappers
        total += apply_file(f, plain)
    with (REPO / "refs/index-see-entries.tex").open("w", encoding="utf-8") as fh:
        fh.write("% generated by tools/apply_index.py — cross-reference index entries\n")
        for key, target in see:
            # '!' is a makeindex special; in see-text render subentries as ", "
            fh.write("\\index{%s|see{%s}}\n" % (key, target.replace("!", ", ")))
    print(f"inserted {total} \\aidx entries from {len(plain)} terms; "
          f"{len(see)} see-entries written")

if __name__ == "__main__":
    main()
