"""Verification of every mathematical claim used in the D_4 scalar problems."""
import itertools, numpy as np, sympy as sp

p1,p2,p3,p4 = sp.symbols('p1 p2 p3 p4', real=True)
p = sp.Matrix([p1,p2,p3,p4])
psq = sum(x**2 for x in p)

# ---------- shells of D_4 -------------------------------------------------
pts = [v for v in itertools.product(range(-3,4), repeat=4) if sum(v) % 2 == 0]
from collections import Counter
norms = Counter(sum(x*x for x in v) for v in pts if any(v))
print("D4 shell counts (norm^2: multiplicity):",
      {k: norms[k] for k in sorted(norms)[:5]})

shell1 = [v for v in pts if sum(x*x for x in v) == 2]
shell2 = [v for v in pts if sum(x*x for x in v) == 4]
print("shell1 size", len(shell1), " shell2 size", len(shell2))
print("shell2 types:", Counter(tuple(sorted(map(abs,v))) for v in shell2))

# ---------- moment sums over shell 1 --------------------------------------
def moment(shell, n):
    return sp.expand(sum((sum(e[i]*p[i] for i in range(4)))**n for e in shell))

m2 = moment(shell1,2); m4 = moment(shell1,4); m6 = moment(shell1,6)
print("\nD4 shell1  sum (p.e)^2 - 12 p^2      =", sp.simplify(m2 - 12*psq))
print("D4 shell1  sum (p.e)^4 - 12 (p^2)^2  =", sp.simplify(m4 - 12*psq**2))

# is the sextic moment a multiple of (p^2)^3 ?  -> no; extract invariant
c = sp.symbols('c')
resid = sp.simplify(m6 - sp.Rational(1,1)*c*psq**3)
sol = sp.solve(sp.Poly(sp.expand(m6 - c*psq**3), p1,p2,p3,p4).coeff_monomial(p1**6), c)
print("D4 shell1  sum (p.e)^6 : coefficient matching (p^2)^3 on p1^6 gives c =", sol)
m6_resid = sp.expand(m6 - sol[0]*psq**3)
print("           residual (genuine F4 degree-6 invariant), nonzero:",
      sp.simplify(m6_resid) != 0)
print("           residual =", sp.factor(sp.simplify(m6_resid)))

# ---------- hypercubic comparison -----------------------------------------
hyper = [v for v in itertools.product([-1,0,1], repeat=4) if sum(abs(x) for x in v)==1]
h2 = moment(hyper,2); h4 = moment(hyper,4)
print("\nhypercubic sum (p.e)^2 =", sp.simplify(h2), " (=2 p^2)")
print("hypercubic sum (p.e)^4 =", sp.simplify(h4), " -> anisotropic at quartic order")
print("hypercubic quartic minus isotropic part:",
      sp.simplify(h4 - sp.Rational(2,3)*psq**2))

# ---------- full kernels, small-p expansion --------------------------------
a = sp.symbols('a', positive=True)
K_d4 = sum(2*(1-sp.cos(a*sum(e[i]*p[i] for i in range(4)))) for e in shell1)
K_hc = sum(2*(1-sp.cos(a*sum(e[i]*p[i] for i in range(4)))) for e in hyper)
ser_d4 = sp.series(K_d4, a, 0, 7).removeO()
ser_hc = sp.series(K_hc, a, 0, 7).removeO()
print("\nD4 kernel a^2 coeff / p^2 :", sp.simplify(sp.expand(ser_d4).coeff(a,2)/psq))
print("D4 kernel a^4 coeff       :", sp.factor(sp.simplify(sp.expand(ser_d4).coeff(a,4))))
print("HC kernel a^4 coeff       :", sp.factor(sp.simplify(sp.expand(ser_hc).coeff(a,4))))

# ---------- automorphism group order & invariant degrees -------------------
# Aut(D4) generated by coordinate permutations, even sign changes, and the
# "triality" reflection  x -> x - (sum x_i) * (1,1,1,1)/2  composed with scaling.
import numpy.linalg as la
gens = []
for perm in [(1,0,2,3),(1,2,3,0)]:
    M = np.zeros((4,4));
    for i,j in enumerate(perm): M[i,j] = 1
    gens.append(M)
S = np.diag([1,1,-1,-1.0]); gens.append(S)
H = np.array([[.5,.5,.5,.5],[.5,.5,-.5,-.5],[.5,-.5,.5,-.5],[.5,-.5,-.5,.5]])
gens.append(H)
group = {tuple(np.round(np.eye(4),9).flatten())}
frontier = [np.eye(4)]
while frontier:
    new = []
    for g in frontier:
        for h in gens:
            m = np.round(h@g, 9)
            t = tuple(m.flatten())
            if t not in group:
                group.add(t); new.append(m)
    frontier = new
print("\n|Aut(D4)| (as generated) =", len(group), " expected 1152 = |W(F4)|")

# Molien-free check: dimension of degree-d invariants under the group
def invariant_dim(deg):
    mons = [m for m in itertools.combinations_with_replacement(range(4), deg)]
    idx = {m:i for i,m in enumerate(mons)}
    basis = []
    for m in mons:
        poly = sp.prod([p[i] for i in m])
        basis.append(sp.Poly(sp.expand(poly), p1,p2,p3,p4))
    # average over group, collect distinct symmetrized polys, get rank
    rows = []
    Gl = [np.array(g).reshape(4,4) for g in group]
    for m in mons:
        acc = sp.Integer(0)
        for g in Gl:
            sub = {p[i]: sum(sp.Rational(round(g[j,i]*2),2)*p[j] for j in range(4)) for i in range(4)}
            acc += sp.prod([sub[p[i]] for i in m])
        acc = sp.expand(acc/len(Gl))
        if acc != 0:
            rows.append(sp.Poly(acc, p1,p2,p3,p4).as_dict())
    allmon = sorted({k for r in rows for k in r})
    M = sp.Matrix([[r.get(k,0) for k in allmon] for r in rows])
    return M.rank()

for d in [2,4,6]:
    print(f"  dim of degree-{d} invariants:", invariant_dim(d))
